### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by rtfpessoa** [timols/java-gitlab-api#109]
Hi @timols,

I started your great api client and just noticed there is a fix for the comments `line_type` still not released.
When are you planning to release this? Would really appreciate if you could do this asap.

**Comment by timols** [comment]
@rtfpessoa coming very soon! Will update you here when it has been released

**Comment by rtfpessoa** [comment]
Thank you :+1:

**Comment by timols** [comment]
Released today!
