### ISSUE TITLE
Search Project by project name not working

### ISSUE THREAD

**Issue by rajiff** [timols/java-gitlab-api#110]
This is a enhancement, not knew where to raise it

Scenario, app only know project name or HTTP URL of the project, have to check if the project exists or not before checking out 

No API wrapper method exists to achieve this

Will be helpful if can be provided

Eg:  http://gitlabexample.com/api/v3/projects/search/SampleProject/?per_page=1&page=1&private_token=TEST_TOKEN

I tried directly as below, which failed though

String myProjectName = "TestProject";
			GitlabProject project = api.retrieve()
			.with("per_page", "1")
			.with("page", "1")
			.to( (GitlabProject.URL + "/search/" + myProjectName), GitlabProject.class);

Not sure whats the reason

**Comment by timols** [comment]
Sure, sounds like a reasonable addition.

I'd be happy to merge the PR if you'd be willing to contribute the enhancement! :+1:
