### ISSUE TITLE
GitlabGroup instantiation fails if a group's ldap_access is null

### ISSUE THREAD

**Issue by MadhavGitlab** [timols/java-gitlab-api#117]
We have groups which have ldap_access with value null, as these groups are not associated with ldap. When i try to get the list of groups from our gitlab using API, it blows up at setLdapAccess(GitlabAccessLevel ldapGitlabAccessLevel). When i add a condition to check if "ldapGitlabAccessLevel' is null, GitlabGroup object is created fine. Will this issue be fixed? or i can submit a fix.

**Comment by timols** [comment]
@MadhavGitlab please feel free to submit a fix! Thanks!

**Comment by iwarapter** [comment]
Hi When will the new version with the fix be released?
