### ISSUE TITLE
Add new "default_branch" parameter to GitlabAPI.updateProject()

### ISSUE THREAD

**Issue by sstafford** [timols/java-gitlab-api#127]
The Gitlab REST API supports the ability to set a default branch for a project.  This allows Gitlab to display the README.md from the default branch when viewing the project.  Please enhance the existing GitlabAPI.updateProject() method to include an additional argument for the default branch.

The Gitlab REST API documents the "default_branch" field here:
http://doc.gitlab.com/ce/api/projects.html#edit-project

**Comment by timols** [comment]
Hi! Thanks for opening this issue. I'd be happy to look at a PR if you'd like to contribute one!

**Comment by sstafford** [comment]
Pull request has been created:  https://github.com/timols/java-gitlab-api/pull/128
