### ISSUE TITLE
Default password not exist

### ISSUE THREAD

**Issue by FranclisJunior** [timols/java-gitlab-api#129]
Hello guys,

I have the following problem:

Before the update gitlab I created a section with the default User's gitlab (root, 5iveL! Fe).
```
String username = "root";
String password = "5iveL!fe";

URI uri = new URI("http://10.100.100.119:8001");
GitlabSession sessionRoot = GitlabAPI.connect(uri.toString(), username, password);
String myToken = sessionRoot.getPrivateToken()
```

However after upgrading gitlab the default password (5iveL! Fe) has been disabled and the first access to gitlab is prompted to change the default password. That is, I can no longer create a section with the default User gitlab(root, 5iveL! Fe). Any solution?

**Comment by rockwotj** [comment]
You can directly get a user's private token via your profile page `/profile/account`. You can see [this link](http://docs.gitlab.com/ce/api/#authentication) for more information about authentication for the API.
