### ISSUE TITLE
Build artifacs

### ISSUE THREAD

**Issue by Confucij** [timols/java-gitlab-api#139]
Is it any way to download build artifact?

**Comment by rockwotj** [comment]
See [this method](https://github.com/timols/java-gitlab-api/blob/master/src/main/java/org/gitlab/api/GitlabAPI.java#L658). You'll download the bytes for the zip file, you need to save that as a zip on your filesystem, then unzip it to get individual artifacts.

**Comment by Confucij** [comment]
@rockwotj Thank you. I see It was not added to 1.2.5 and still not tagged.
