### ISSUE TITLE
Single Responsibility Principle

### ISSUE THREAD

**Issue by tstivers1990** [timols/java-gitlab-api#142]
This class is a major violation of single responsibility principle.

https://github.com/timols/java-gitlab-api/blob/master/src/main/java/org/gitlab/api/GitlabAPI.java

If you want some ideas on a better way to do it, you can view my current project which is in C#.

https://gitlab.com/tstivers/GitLab.NET

https://en.wikipedia.org/wiki/Single_responsibility_principle

**Comment by timols** [comment]
@tstivers1990 thanks for raising this as an issue. Would you be interested in taking on the challenge of making sure that it doesn't violate SRP?

**Comment by tstivers1990** [comment]
@timols Not really. I'm busy writing my own wrapper in C#. I just wanted to point it out more to educate than to criticize.

**Comment by timols** [comment]
Ok great. Thanks.
