### ISSUE TITLE
Release soon?

### ISSUE THREAD

**Issue by krische** [timols/java-gitlab-api#149]
Any chance you can release an update soon? It looks like a lot of functionality has been added since 1.2.5 and it would be nice to get that from the release package.

**Comment by avitsidis** [comment]
Totally agree with krische. A release like 1.2.6 with the latest changes on maven-central would be nice

**Comment by timols** [comment]
@krische @avitsidis coming soon!

**Comment by timols** [comment]
Released today! Should be available on maven central shortly
