### ISSUE TITLE
GitlabAPI  getAllProjects method spend long time

### ISSUE THREAD

**Issue by shark-yu** [timols/java-gitlab-api#162]
Hi, There is about 286 projects, I use `GitlabAPI getAllProjects` method to get all projects, It spend 10 seconds about.

**Comment by mfriedenhagen** [comment]
I think gitlab might be slow here. We have about 1800 projects and retrieving the first one hundred already takes about 3 seconds. This is the same when you use curl, so...

**Comment by shark-yu** [comment]
Oh, I am sorry, you are right, I have verified it, thanks for your help.

**Comment by mfriedenhagen** [comment]
Hey, I would like to reopen the issue. At least this library could try to use three instead of 15 calls, which will speed up retrieval a bit.

**Comment by shark-yu** [comment]
ok

**Comment by johnou** [comment]
@mfriedenhagen might be solved with the latest version of the API, I don't see any reference to 15 anywhere, from what I see Pagination defaults to 100.

**Comment by johnou** [comment]
@shark-yu please try 1.2.7 and see if things are faster.

**Comment by mfriedenhagen** [comment]
@johnou, according to  the documentation https://docs.gitlab.com/ce/api/README.html#pagination the default seems to be 20 per page, so 15 calls for ca. 300 projects, this corresponds to my experience as well. The maximum is 100.

**Comment by johnou** [comment]
@mfriedenhagen yep but the default in this project is 100 https://github.com/timols/java-gitlab-api/blob/master/src/main/java/org/gitlab/api/Pagination.java#L10 unless the API endpoint is being called without any pagination params?

**Comment by johnou** [comment]
@mfriedenhagen I've managed to set this up locally, will come up with a generic fix and create a pull request soon.

**Comment by johnou** [comment]
@timols there are potentially 23 usages of org.gitlab.api.http.GitlabHTTPRequestor#getAll which could be optimized by sending the Pagination param in the payload with the items per page as 100, I think this should be the default for all API requests which recursively collect all items, wdyt?

**Comment by timols** [comment]
@johnou sounds like a plan. Looking forward to the PR!

**Comment by johnou** [comment]
cheeky @timols :) here it is https://github.com/timols/java-gitlab-api/issues/195
