### ISSUE TITLE
Webhooks/Events

### ISSUE THREAD

**Issue by hadesrofl** [timols/java-gitlab-api#168]
Hey,

I had a look at the Documentation in JavaDoc but am still wondering if this wrapper supports webhooks?

I'd like to write an app that listens to events like a commit or change on an issue and wonder if it's currently supported by this lib.

Thanks in advance.

**Comment by timols** [comment]
@hadesrofl the latest release now has support for adding webhooks to a project programmatically. I hope that satisfies your needs. If you need support for handling the request that comes from the webhook, I'd be happy to take a look at a PR
