### ISSUE TITLE
How to modify a project

### ISSUE THREAD

**Issue by Teudimundo** [timols/java-gitlab-api#171]
I've seen there GitLabApi was previously providing tools for setting project options and for updating them, but this is now deprecated. 

Is there another way to set project parameters or update them? Why were the methods deprecated?

**Comment by sstafford** [comment]
I have the same question.

**Comment by timols** [comment]
@Teudimundo @sstafford I think those questions are best for the Gitlab project itself. This is only a wrapper around the REST api and I have no insight into the API itself.

**Comment by Teudimundo** [comment]
I think this is the appropriate place, since the Gitlab REST API actually provides an edit endpoint for projects:

https://docs.gitlab.com/ee/api/projects.html#edit-project

And this is not deprecated.
