### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by johnou** [timols/java-gitlab-api#200]
Would you kindly release 1.2.8? It is currently blocking us from adopting your API to the sonar-gitlab-plugin project. Thanks in advance!

**Comment by johanneslanger** [comment]
Same here, release would be great as we need the proxy support!

**Comment by johnou** [comment]
@timols poke

**Comment by timols** [comment]
@johnou released! Sorry for the delay. Should be available in maven central shortly.

**Comment by johnou** [comment]
@timols thanks, hope you had a great Easter!
