### ISSUE TITLE
Support API v4

### ISSUE THREAD

**Issue by tomasbjerre** [timols/java-gitlab-api#201]
V3 is deprecated; https://about.gitlab.com/2017/03/22/gitlab-9-0-released/

**Comment by jsorah** [comment]
Linking to GitLab CE API [v3 to v4 Changes](https://docs.gitlab.com/ce/api/v3_to_v4.html) for more context.

**Comment by timols** [comment]
Thanks @tomasbjerre. Would you be willing to submit a PR to upgrade to v4?

Should be a relatively easy change based on the link from @jsorah

**Comment by tomasbjerre** [comment]
Perhaps. I cannot promise anything. But yes, if I find the time.

**Comment by mfriedenhagen** [comment]
As I wrote in #201, I suggest to bump the major of java-gitlab-api to 4, so it corresponds to the API level.

**Comment by timols** [comment]
@mfriedenhagen 👏 👏 great work!

More than happy for you to bump the version to v4.

**Comment by timols** [comment]
This is now in master. Once we've worked out any issues I'll create a release.

**Comment by tomasbjerre** [comment]
Thanks! :)

**Comment by tomasbjerre** [comment]
Will you also release 4.0 soon?
