### ISSUE TITLE
Issue with uploadFile function in GITLAB API

### ISSUE THREAD

**Issue by surajs5000** [timols/java-gitlab-api#205]
Hi ! I am trying to use the uploadFile function of the GITLAB API. But it is throwing a exception saying No references. Can you please help me out ?

I am using java-gitlab-api 1.2.8

**Comment by timols** [comment]
Hi @surajs5000,

What version of Gitlab are you running?

**Comment by surajs5000** [comment]
Hi @timols 

I am GITLAB Community edition 8.8.3 374d212

**Comment by surajs5000** [comment]
* I am using

**Comment by surajs5000** [comment]
@timols Is the uploadFile designed to work with newer versions of Gitlab ?

**Comment by surajs5000** [comment]
Closing this issue. Found the problem and fixed it.
