### ISSUE TITLE
Publish jar with API v4 support

### ISSUE THREAD

**Issue by jpitz** [timols/java-gitlab-api#222]
I see a fair number of commits regarding API v4 support but based on the version that I see in maven central, it looks like it still only supports v3. Once a stable v4 is available, can we get an announcement / changelog of what's changed with this client jar?

**Comment by tomasbjerre** [comment]
@timols What is the status? Need help? Will this happen before v3 is removed?

**Comment by aram535** [comment]
Gitlab is removing V3 APIs as of Gitlab 11.0 (10.0 was released today).
[https://about.gitlab.com/2017/09/22/gitlab-10-0-released/#api-v3](https://about.gitlab.com/2017/09/22/gitlab-10-0-released/#api-v3)

**Comment by timols** [comment]
Released today!

**Comment by DuaneOBrien** [comment]
Thanks!
