### ISSUE TITLE
Exceptions should never be propagated as a generic Java Error

### ISSUE THREAD

**Issue by jpitz** [timols/java-gitlab-api#275]
This tends to cause processes to crash as no-one catches this type of error. From what I can tell, it looks like we are re-boxing the GitlabAPIexception with a java.lang.Error.

```
java.lang.Error: org.gitlab.api.GitlabAPIException: {"message":"403 Forbidden"}
	at org.gitlab.api.http.GitlabHTTPRequestor$1.fetch(GitlabHTTPRequestor.java:263)
	at org.gitlab.api.http.GitlabHTTPRequestor$1.hasNext(GitlabHTTPRequestor.java:217)
	at org.gitlab.api.http.GitlabHTTPRequestor.getAll(GitlabHTTPRequestor.java:185)
	at org.gitlab.api.GitlabAPI.getRepositoryTree(GitlabAPI.java:1563)
```

**Comment by jpitz** [comment]
Looking at the code really quick, I see this double try catch causing the issue:

```
                try {
                    HttpURLConnection connection = setupConnection(url);
                    try {
                        next = parse(connection, type, null);
                        assert next != null;
                        findNextUrl();
                    } catch (IOException e) {
                        handleAPIError(e, connection);
                    }
                } catch (IOException e) {
                    throw new Error(e);
                }
```

**Comment by timols** [comment]
@jpitz you make a very good point. Would you be ok to submit a PR for this change?

**Comment by jpitz** [comment]
I can look at putting one together. Will comment back once I have one.

**Comment by jpitz** [comment]
@timols : feel free to assign to me if possible. I should have something up today.

**Comment by jpitz** [comment]
Pull request here: https://github.com/timols/java-gitlab-api/pull/281

**Comment by jaredhodge** [comment]
@timols ; how about spinning a new version of the library and propagating it out maven central so people can take advantage of this fix?

**Comment by jaredhodge** [comment]
I see 4.1.0 out there now.  Thanks @timols!
