### ISSUE TITLE
Improving Apache 2.0 Licensing Information

### ISSUE THREAD

**Issue by PhilMFischer** [timols/java-gitlab-api#285]
The statements for this libraries license can be improved.

It is good practice to place the applicapble license to the bundle and ship it together with the source and binary. In this case the Apache 2.0 license text.

Following the Apache Guide ( http://www.apache.org/dev/licensing-howto.html#mod-notice ), I see the following that needs to be done:
1 - The current content of the LICENSE file should be refactored into the NOTICE file. 
2 - The current LICENSE file should be replaced by the actual Apache 2.0 license.

**Comment by timols** [comment]
Thank you for doing this!
