### ISSUE TITLE
Release 4.x.x for depending projects

### ISSUE THREAD

**Issue by PhilMFischer** [timols/java-gitlab-api#289]
The eclipse mylyn-gitlab connector is based on this java-gitlab-api library. See: https://github.com/pweingardt/mylyn-gitlab

Due to the latest changes in #284 and #285 some issues in the mylyn-gitlab connector, in particluar https://github.com/pweingardt/mylyn-gitlab/issues/47 ,could be fixed.

A new Release of this library is highly appreciated. :grin:

I am happy to help, but have no clue on how to trigger a Release. :confused:

**Comment by lamdaV** [comment]
I am in a similar boat would like to use some of the latest features added to my project.

**Comment by zapelin** [comment]
+1

**Comment by maba001** [comment]
+1

**Comment by tomasbjerre** [comment]
Perhaps you are already familiar with Jitpack: https://jitpack.io/#timols/java-gitlab-api/master-SNAPSHOT But I would also prefer it if my projects could depend only on Maven Central!

Perhaps the release strategy can be changed to do, maby, **beta** releases? Something that can be done for every merged PR and simply by relying on the automated tests.

@OlgaMaciaszek @timols Why don't you do releases more frequent?

**Comment by timols** [comment]
Released today

**Comment by OlgaMaciaszek** [comment]
@tomasbjerre I'm not a committer or maintainer of this project. I just contribute the things that I think should be added there. I suspect @timols maintains this project in his free time on top of many other things he does so, as always with open source, it's better to offer help and participate rather than criticize.
