### ISSUE TITLE
Files containing spaces in their path are wrongly encoded

### ISSUE THREAD

**Issue by slauriere** [timols/java-gitlab-api#331]
When file paths are sent to GitLab, their path gets encoded using the default java.net.URLEncoder which is [documented](https://docs.oracle.com/javase/8/docs/api/java/net/URLEncoder.html) as "an utility for HTML form encoding". However, URL form encoding differs from path encoding at least concerning the way spaces get encoded, as explained in details in [this stackoverflow post](https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20/29948396#29948396). This means that the method ["sanitizePath" of GitlabAPI](https://github.com/timols/java-gitlab-api/blob/master/src/main/java/org/gitlab/api/GitlabAPI.java#L3276) should take this into account and convert "+" characters into the string "%20".

**Comment by aubincleme** [comment]
Hi
@timols any update on this ? It seems that my team has the same issue.

Thanks !

**Comment by slauriere** [comment]
The fix was integrated in the latest release (4.1.1) – see [GitLapAPI.java#L3441](https://github.com/timols/java-gitlab-api/blob/4.1.1/src/main/java/org/gitlab/api/GitlabAPI.java#L3441) – so I'm marking this issue as closed.
