### ISSUE TITLE
getProjects() and getAllProjects() spend a long time running giving no response

### ISSUE THREAD

**Issue by Iruora** [timols/java-gitlab-api#340]
Hello, I'm using the API in a Java Spring Boot Maven project with the version 4.1.0 of the "java-gitlab-api" dependency.
The problem is as I've specified in the issue's title is that the getProjects() and getAllProjects() spend a long time running, even forever giving no response and push me to stop the application noting that I am only having five projects under my account so it's not a problem of a query that's retrieving a huge amount of data.

**Comment by pascalwhoop** [comment]
it doesn't fetch your projects but all those that you have access to. Did you point this to gitlab.com? Because that instance has *a lot* of projects ...
