### ISSUE TITLE
Please publish the next release

### ISSUE THREAD

**Issue by rkpatel7** [timols/java-gitlab-api#362]
This is similar to #200. 

It's been more than a year since the last release published to [maven](https://mvnrepository.com/artifact/org.gitlab/java-gitlab-api) (`4.1.0`) and since then there have been multiple changes made and merged to master:

* `4.1.0` tag: https://github.com/timols/java-gitlab-api/tree/4.1.0
* master: https://github.com/timols/java-gitlab-api/tree/master

@timols can you please release the next version? Thanks!

**Comment by timols** [comment]
Yes, will do this weekend!

**Comment by rkpatel7** [comment]
Thanks! Would you be able take a look at the open pull requests and merge them in before releasing the new version? Selfishly I would like https://github.com/timols/java-gitlab-api/pull/361 to be merged in before the release is published but the checks did fail and would need to be re-run. It appears to have failed at installing jdk.

**Comment by rkpatel7** [comment]
@timols I was able to fix the failing check in #363 by switching to `openjdk` in the travis config on that branch. I think we should merge that in so future PRs will also be able to take advantage of the fix.

**Comment by timols** [comment]
Done! I think your suggestion is a good one.

**Comment by rkpatel7** [comment]
@timols hi do you have any update on getting the next release published? Thanks!

**Comment by timols** [comment]
@rkpatel7 Done! I just release v4.1.1 today

**Comment by rkpatel7** [comment]
Thanks!
