### ISSUE TITLE
Edit project team member

### ISSUE THREAD

**Issue by lusaczek** [timols/java-gitlab-api#40]
Hi.
I search possibile how to edit privileges user into group.
I find solution but I don't see how to do work in your api

From api (there is PUT but in your URL is only POST):
Edit project team member
Updates a project team member to a specified access level.
PUT /projects/:id/members/:user_id
Parameters:
id (required) - The ID or NAMESPACE/PROJECT_NAME of a project
user_id (required) - The ID of a team member
access_level (required) - Project access level

best regards s.

**Comment by timols** [comment]
Hi @lusaczek, happy to add this if you'd like to submit a pull request.
