### ISSUE TITLE
ignoreCertificateErrors is not complete

### ISSUE THREAD

**Issue by renier** [timols/java-gitlab-api#44]
If the hostname (or IP) being used does not match the hostname in the certificate, ignoreCertificateErrors will not do enough to avoid an SSL certificate exception.

Need to add this:

```java
HostnameVerifier nullVerifier = new HostnameVerifier() {
    @Override
    public boolean verify(String hostname, SSLSession session) {
        return true;
    }
};
// ...
HttpsURLConnection.setDefaultHostnameVerifier(nullVerifier);
```
to [GitlabHTTPRequestor](https://github.com/timols/java-gitlab-api/blob/master/src/main/java/org/gitlab/api/http/GitlabHTTPRequestor.java#L328)

**Comment by roanosullivan** [comment]
+1 I also encountered this.
