### ISSUE TITLE
createMergeRequest operation needed

### ISSUE THREAD

**Issue by simcatalin** [timols/java-gitlab-api#48]
Hi, 
I have a change which I would like to push into master regarding the for createMergeRequest operation. How can I get access to do that?

**Comment by timols** [comment]
Hi @simcatalin, sure I'm happy to accept a pull request for that feature - if you're not sure how to do that, you should read about how to open a pull request with Github (https://help.github.com/articles/creating-a-pull-request/)

**Comment by MadhavGitlab** [comment]
was this work done?

**Comment by timols** [comment]
@MadhavGitlab no it hasn't.
