### ISSUE TITLE
Ignoring GET params when List repository tree request

### ISSUE THREAD

**Issue by vmusil** [timols/java-gitlab-api#56]
According to the documentation in the 'List Repository Tree section' (http://doc.gitlab.com/ce/api/repositories.html) it is possible to define the 'path' attribute to List files/dirs in some directory. Because it's GET request the params must be appended to the url by ? and & chars the same way like 'private_token'. Currently the GET params seems to be ignored (I get only the file in the root dir) when building the request like: 

String tailUrl = GitlabProject.URL + "/" + projectId + "/" + "repository" + "/" + "tree";
getConnection().dispatch()
			.method("GET")
			.with("id", projectId)
			.with("path", path)
			.with("ref_name", branchName)
			.to(tailUrl, ListFilesResponse[].class);

I'm using the last 1.1.4 version from maven repo (http://mvnrepository.com/artifact/org.gitlab/java-gitlab-api).

Thank you

**Comment by timols** [comment]
Happy to review a Pull Request if you'd like to submit one.

**Comment by gsmet** [comment]
@vmusil I think you're doing it wrong: you need to use Query and append it to your URL. You have a tons of examples in GitlabAPI.

It would be nice if you could contribute your code!

**Comment by gsmet** [comment]
@timols looks like we can close this one because it has been implemented in https://github.com/timols/java-gitlab-api/pull/69 .

**Comment by timols** [comment]
Ok, thanks @gsmet!
