### ISSUE TITLE
Could you please publish last stable version to maven central?

### ISSUE THREAD

**Issue by pabloa** [timols/java-gitlab-api#58]
Is this project alive? Could you publish a new version to maven central?

**Comment by pabloa** [comment]
I found version 1.1.8 :) so project is alive. Please publish that version to some maven repo :D

**Comment by timols** [comment]
Will do. Have been working through some deployment issues recently and should have it ready to go this weekend.

**Comment by KostyaSha** [comment]
any updates?

**Comment by timols** [comment]
Released today. Apologies for the delay
