### ISSUE TITLE
retrieving of BLOBs, retrieving zip archives

### ISSUE THREAD

**Issue by matejsp** [timols/java-gitlab-api#68]
Support for downloading git file blobs:

http://doc.gitlab.com/ce/api/repositories.html#raw-file-content
http://doc.gitlab.com/ce/api/repositories.html#raw-blob-content
http://doc.gitlab.com/ce/api/repositories.html#get-file-archive

example call:
/api/v3/projects/74/repository/blobs/develop?filepath=filepath/file.txt

**Comment by timols** [comment]
Thanks @matejsp. PRs always welcome :)

**Comment by mvidmar** [comment]
PR added for this #69
