### ISSUE TITLE
Missing avatar_url for projects

### ISSUE THREAD

**Issue by wikiwi** [timols/java-gitlab-api#78]
I'm currently developing a Jenkins integration. Would be super handy to have the `avatar_url` to spice up the GUI.

**Comment by timols** [comment]
@wikiwi sure - feel free to submit a PR to expose that property since its already included the JSON payload.

**Comment by esarbanis** [comment]
@wikiwi It appears that avatar_url is [exposed](https://github.com/timols/java-gitlab-api/commit/e19011d13014265b61e3465be5c77035691dda52) for quite some time now. Am I missing something?

**Comment by wikiwi** [comment]
@esarbanis the avatar_url of the user is exposed, but the avatar_url of projects is not.
