### ISSUE TITLE
Authentication via Headers

### ISSUE THREAD

**Issue by wikiwi** [timols/java-gitlab-api#79]
This is a feature request to support Authentication via Headers.

My use case:
I'm writing a Jenkins integration using this API wrapper. The current authentication with a GET parameter logs the token all over the place in Jenkins. I'd be happy to hide the token from the logs by moving the authentication data to the Headers.

**Comment by timols** [comment]
Assuming the Gitlab API supports it, then i'd be happy to merge a PR

**Comment by wikiwi** [comment]
I will submit a PR for this soon
